trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      curl -sL https://apt.releases.hashicorp.com/gpg | gpg --dearmor > hashicorp.gpg
      sudo install -o root -g root -m 644 hashicorp.gpg /etc/apt/trusted.gpg.d/
      sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
      sudo apt update && sudo apt install terraform -y

- script: terraform init
  displayName: 'Terraform Init'

- script: terraform validate
  displayName: 'Terraform Validate'

- script: terraform plan -out=tfplan.out
  displayName: 'Terraform Plan'
